micronaut:
  application:
    name: oda-config-server
  security:
    token:
      bearer:
        enabled: true
      cookie:
        enabled: true
      jwt:
        signatures:
          jwks:
            keycloak:
              url: https://auth.oda.digital/realms/ODA/protocol/openid-connect/certs
datasources:
  default:
    url: ${JDBC_URL}
    username: ${JDBC_USER:`postgres`}
    password: ${JDBC_PASSWORD:`postgres`}
    db-type: "postgresql"
    driverClassName: 'org.postgresql.Driver'
endpoints:
  flyway:
    enabled: true
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
jpa:
  default:
    entity-scan:
        packages: 'io.github.stcarolas.oda.config'
