micronaut:
  application:
    name: oda-config-server
  security:
    token:
      bearer:
        enabled: true
      cookie:
        enabled: true
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${JWKS_URI}
endpoints:
  flyway:
    enabled: true
datasources:
  default:
    schema: 'config'
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      schemas: 'config'
      default-schema: 'config'
jpa:
  default:
    entity-scan:
        packages: 'io.github.stcarolas.oda.config'
